name: Build All Sites

on:
  push:
    branches: [ master ]

jobs:
  build-warwick:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build project
        run: |
          npm install
          mv "src/regions/warwick.js" "src/settings.js"
          npm run build
        
      - name: push to gh pages repo
        uses: uow-covid19/github-action-push-to-another-repository@master
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'build'
          destination-github-username: 'uow-covid19'
          destination-repository-name: 'uow-covid19.github.io'
          user-email: buildbot@example.com

  build-others:
    runs-on: ubuntu-latest
    needs: build-warwick
    strategy:
      matrix:
        regions: ['liverpool', 'manchester']

    steps:
      - uses: actions/checkout@v2

      - name: Build project
        run: |
          npm install
          mv "src/regions/${{ matrix.regions }}.js" "src/settings.js"
          mv "src/packages/${{ matrix.regions }}.json" "package.json"
          npm run build

      - name: push to gh pages repo
        uses: uow-covid19/github-action-push-to-another-repository@master
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'build'
          destination-github-username: 'uow-covid19'
          destination-repository-name: 'uow-covid19.github.io'
          user-email: buildbot@example.com
          target-directory: ${{ matrix.regions }}