name: Build All Sites

on:
  push:
    branches: [ master ]

jobs:
  get-sites:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.find-sites.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2

      - id: find-sites
        run: echo '::set-output name=matrix::["warwick"]'

  build-sites:
    runs-on: ubuntu-latest
    needs: get-sites
    strategy:
      matrix:
        regions: ${{ fromJson(needs.get-sites.outputs.matrix) }}

    steps:
      - uses: actions/checkout@v2

      - name: Build project
        run: |
          npm install
          mv "src/regions/${{ matrix.regions }}.js" "src/settings.js"
          mv "src/packages/${{ matrix.regions }}.json" "package.json"
          npm run build

      - name: push to gh pages repo
        uses: uow-covid19/github-action-push-to-another-repository@master
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'build'
          destination-github-username: 'uow-covid19'
          destination-repository-name: 'uow-covid19.github.io'
          user-email: buildbot@example.com
          target-branch: 'staging'
          target-directory: ${{ matrix.regions }}

  # merge-staging:
  #   runs-on: ubuntu-latest
  #   needs: build-sites

  #   steps:
  #     - name: merge staging into master
  #       env:
  #         API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
  #       run: |
  #         CLONE_DIR=$(mktemp -d)
  #         git config --global user.email "uow-covid19mergebot@example.com"
  #         git config --global user.name "uow-covid19mergebot"
  #         git clone "https://$API_TOKEN_GITHUB@github.com/uow-covid19/uow-covid19.github.io.git" "$CLONE_DIR"
  #         cd $CLONE_DIR
  #         git checkout master
  #         git merge origin/staging
  #         git push origin master

