name: Liverpool Build

on:
  push:
    branches: [ liverpool ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build project
        run: |
          npm install
          npm run build
        
      - name: push to gh pages repo
        uses: uow-covid19/github-action-push-to-another-repository@v1.2
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'build'
          destination-github-username: 'uow-covid19'
          destination-repository-name: 'uow-covid19.github.io'
          user-email: buildbot@example.com
          target-directory: 'liverpool'